"""initial

Revision ID: 3f50c5b2621e
Revises: 
Create Date: 2025-11-21 11:12:32.264305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f50c5b2621e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('to_url', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_from_name'), 'urls', ['from_name'], unique=True)
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_from_name'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
